# Generated by Django 5.2.1 on 2025-05-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_workout_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workoutId',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='exerciseId',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='userId',
            new_name='user',
        ),
    ]
