# Generated by Django 5.2.1 on 2025-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_workoutid_exercise_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='time',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.AddField(
            model_name='set',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Exercise', max_length=255),
        ),
    ]
